version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306        #  $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: wordpress      #  $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: wp_user        #  $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: wp_pass    #  $WORDPRESS_DB_PASSWORD

volumes:
  db_data:
